%{
  configs: [
    %{
      name: "default",
      plugins: [{AshCredo, []}],
      checks: %{
        enabled: [
          {ExDNA.Credo, false},
          {CredoNaming.Check.Consistency.ModuleFilename, false},
          {Credo.Check.Design.DuplicatedCode, false},
          {ExSlop.Check.Warning.BlanketRescue, []},
          {ExSlop.Check.Warning.RescueWithoutReraise, []},
          {ExSlop.Check.Warning.RepoAllThenFilter, []},
          {ExSlop.Check.Warning.QueryInEnumMap, []},
          {ExSlop.Check.Warning.GenserverAsKvStore, []},
          {ExSlop.Check.Refactor.FilterNil, []},
          {ExSlop.Check.Refactor.RejectNil, []},
          {ExSlop.Check.Refactor.ReduceAsMap, []},
          {ExSlop.Check.Refactor.MapIntoLiteral, []},
          {ExSlop.Check.Refactor.IdentityPassthrough, []},
          {ExSlop.Check.Refactor.IdentityMap, []},
          {ExSlop.Check.Refactor.CaseTrueFalse, []},
          {ExSlop.Check.Refactor.TryRescueWithSafeAlternative, []},
          {ExSlop.Check.Refactor.WithIdentityElse, []},
          {ExSlop.Check.Refactor.WithIdentityDo, []},
          {ExSlop.Check.Refactor.SortThenReverse, []},
          {ExSlop.Check.Refactor.StringConcatInReduce, []},
          {ExSlop.Check.Readability.NarratorDoc, false},
          {ExSlop.Check.Readability.DocFalseOnPublicFunction, []},
          {ExSlop.Check.Readability.BoilerplateDocParams, []},
          {ExSlop.Check.Readability.ObviousComment, []},
          {ExSlop.Check.Readability.StepComment, []},
          {ExSlop.Check.Readability.NarratorComment, []},
          {Credo.Check.Design.TagTODO, false},
          {Credo.Check.Design.TagFIXME, false},
          {AshCredo.Check.Warning.AuthorizeFalse,
           [excluded_paths: [~r{/(test|deps|_build)/}, ~r/_test\.exs$/]]},
          {AshCredo.Check.Warning.AuthorizerWithoutPolicies, []},
          {AshCredo.Check.Warning.EmptyDomain, []},
          {AshCredo.Check.Warning.MissingDomain, []},
          {AshCredo.Check.Warning.NoActions, []},
          {AshCredo.Check.Warning.OverlyPermissivePolicy, []},
          {AshCredo.Check.Warning.SensitiveAttributeExposed, []},
          {AshCredo.Check.Warning.SensitiveFieldInAccept, []},
          {AshCredo.Check.Warning.UnknownAction, []},
          {AshCredo.Check.Warning.WildcardAcceptOnAction, []},
          {AshCredo.Check.Refactor.DirectiveInFunctionBody, []},
          {AshCredo.Check.Refactor.LargeResource, []},
          {AshCredo.Check.Refactor.RaisingCall, []},
          {AshCredo.Check.Refactor.UseCodeInterface, []},
          {AshCredo.Check.Design.MissingCodeInterface,
           [
             excluded_actions: [
               "Prizmo.Accounts.Token.expunge_expired",
               "Prizmo.Accounts.Token.expired",
               "Prizmo.Accounts.Token.get_confirmation_changes",
               "Prizmo.Accounts.Token.get_token",
               "Prizmo.Accounts.Token.read",
               "Prizmo.Accounts.Token.read_expired",
               "Prizmo.Accounts.Token.revoke_all_stored_for_subject",
               "Prizmo.Accounts.Token.revoke_jti",
               "Prizmo.Accounts.Token.revoke_token",
               "Prizmo.Accounts.Token.revoked?",
               "Prizmo.Accounts.Token.store_confirmation_changes",
               "Prizmo.Accounts.Token.store_token",
               "Prizmo.Accounts.User.get_by_email",
               "Prizmo.Accounts.User.get_by_subject",
               "Prizmo.Accounts.User.log_out_everywhere",
               "Prizmo.Accounts.User.read",
               "Prizmo.Accounts.User.request_magic_link",
               "Prizmo.Accounts.User.sign_in_with_magic_link",
               "Prizmo.Accounts.User.sign_in_with_remember_me"
             ]
           ]},
          {AshCredo.Check.Design.MissingIdentity, [identity_candidates: []]},
          {AshCredo.Check.Design.MissingPrimaryAction, false},
          {AshCredo.Check.Design.MissingTimestamps, false},
          {AshCredo.Check.Readability.ActionMissingDescription, false},
          {AshCredo.Check.Readability.BelongsToMissingAllowNil, []}
        ]
      }
    }
  ]
}
