defmodule Prizmo.Repo.Migrations.AddTcgPlayerTurnFlags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tcg_engine_game_players) do
      add :energy_attached_this_turn?, :boolean, null: false, default: false
      add :supporter_played_this_turn?, :boolean, null: false, default: false
      add :retreated_this_turn?, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:tcg_engine_game_players) do
      remove :retreated_this_turn?
      remove :supporter_played_this_turn?
      remove :energy_attached_this_turn?
    end
  end
end
