defmodule Prizmo.Repo.Migrations.AddTcgSetupReady do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tcg_engine_game_players) do
      add :setup_ready?, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:tcg_engine_game_players) do
      remove :setup_ready?
    end
  end
end
