defmodule Prizmo.Repo.Migrations.AddTcgTurnVisibility do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tcg_engine_turns) do
      add :visible?, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:tcg_engine_turns) do
      remove :visible?
    end
  end
end
