defmodule Prizmo.Repo.Migrations.AddTcgEngine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tcg_engine_turns, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :game_id, :uuid, null: false
      add :turn_number, :bigint, null: false
      add :active_player_id, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :status, :text, null: false, default: "start"
    end

    create unique_index(:tcg_engine_turns, [:game_id, :turn_number],
             name: "tcg_engine_turns_unique_game_turn_number_index"
           )

    create table(:tcg_engine_setups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :game_id, :uuid, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :status, :text, null: false, default: "waiting_to_draw"
    end

    create unique_index(:tcg_engine_setups, [:game_id],
             name: "tcg_engine_setups_unique_game_setup_index"
           )

    create table(:tcg_engine_prompts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :game_id, :uuid, null: false
      add :turn_id, :uuid
      add :prompt_type, :text, null: false
      add :player_id, :text, null: false
      add :payload, :map, null: false, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :status, :text, null: false, default: "awaiting_choice"
    end

    create table(:tcg_engine_games, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:tcg_engine_turns) do
      modify :game_id,
             references(:tcg_engine_games,
               column: :id,
               name: "tcg_engine_turns_game_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tcg_engine_setups) do
      modify :game_id,
             references(:tcg_engine_games,
               column: :id,
               name: "tcg_engine_setups_game_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tcg_engine_prompts) do
      modify :game_id,
             references(:tcg_engine_games,
               column: :id,
               name: "tcg_engine_prompts_game_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :turn_id,
             references(:tcg_engine_turns,
               column: :id,
               name: "tcg_engine_prompts_turn_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tcg_engine_games) do
      add :active_player_id, :text, null: false
      add :first_player_id, :text, null: false
      add :cursor_index, :bigint, null: false, default: 0
      add :latest_event_index, :bigint, null: false, default: 0

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :status, :text, null: false, default: "created"
    end

    create table(:tcg_engine_game_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :game_id,
          references(:tcg_engine_games,
            column: :id,
            name: "tcg_engine_game_snapshots_game_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :game_event_id, :uuid
      add :index, :bigint, null: false
      add :snapshot, :map, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tcg_engine_game_snapshots, [:game_id, :index],
             name: "tcg_engine_game_snapshots_unique_game_snapshot_index_index"
           )

    create table(:tcg_engine_game_players, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :game_id,
          references(:tcg_engine_games,
            column: :id,
            name: "tcg_engine_game_players_game_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :player_id, :text, null: false
      add :deck_key, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tcg_engine_game_players, [:game_id, :player_id],
             name: "tcg_engine_game_players_unique_game_player_index"
           )

    create table(:tcg_engine_game_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:tcg_engine_game_snapshots) do
      modify :game_event_id,
             references(:tcg_engine_game_events,
               column: :id,
               name: "tcg_engine_game_snapshots_game_event_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tcg_engine_game_events) do
      add :game_id,
          references(:tcg_engine_games,
            column: :id,
            name: "tcg_engine_game_events_game_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :turn_id,
          references(:tcg_engine_turns,
            column: :id,
            name: "tcg_engine_game_events_turn_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :index, :bigint, null: false
      add :type, :text, null: false
      add :player_id, :text
      add :payload, :map, null: false, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tcg_engine_game_events, [:game_id, :index],
             name: "tcg_engine_game_events_unique_game_event_index_index"
           )

    create table(:tcg_engine_card_instances, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :game_id,
          references(:tcg_engine_games,
            column: :id,
            name: "tcg_engine_card_instances_game_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :game_player_id,
          references(:tcg_engine_game_players,
            column: :id,
            name: "tcg_engine_card_instances_game_player_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :owner_player_id, :text, null: false
      add :instance_id, :text, null: false
      add :card_id, :text, null: false
      add :position, :bigint, null: false
      add :damage, :bigint, null: false, default: 0
      add :markers, :map, null: false, default: %{}

      add :attached_to_card_instance_id,
          references(:tcg_engine_card_instances,
            column: :id,
            name: "tcg_engine_card_instances_attached_to_card_instance_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :zone, :text, null: false, default: "deck"
    end

    create unique_index(:tcg_engine_card_instances, [:game_id, :instance_id],
             name: "tcg_engine_card_instances_unique_game_instance_index"
           )
  end

  def down do
    drop constraint(:tcg_engine_card_instances, "tcg_engine_card_instances_game_id_fkey")

    drop constraint(:tcg_engine_card_instances, "tcg_engine_card_instances_game_player_id_fkey")

    drop constraint(
           :tcg_engine_card_instances,
           "tcg_engine_card_instances_attached_to_card_instance_id_fkey"
         )

    drop_if_exists unique_index(:tcg_engine_card_instances, [:game_id, :instance_id],
                     name: "tcg_engine_card_instances_unique_game_instance_index"
                   )

    drop table(:tcg_engine_card_instances)

    drop constraint(:tcg_engine_game_events, "tcg_engine_game_events_game_id_fkey")

    drop constraint(:tcg_engine_game_events, "tcg_engine_game_events_turn_id_fkey")

    drop_if_exists unique_index(:tcg_engine_game_events, [:game_id, :index],
                     name: "tcg_engine_game_events_unique_game_event_index_index"
                   )

    alter table(:tcg_engine_game_events) do
      remove :created_at
      remove :payload
      remove :player_id
      remove :type
      remove :index
      remove :turn_id
      remove :game_id
    end

    drop constraint(:tcg_engine_game_snapshots, "tcg_engine_game_snapshots_game_event_id_fkey")

    alter table(:tcg_engine_game_snapshots) do
      modify :game_event_id, :uuid
    end

    drop table(:tcg_engine_game_events)

    drop constraint(:tcg_engine_game_players, "tcg_engine_game_players_game_id_fkey")

    drop_if_exists unique_index(:tcg_engine_game_players, [:game_id, :player_id],
                     name: "tcg_engine_game_players_unique_game_player_index"
                   )

    drop table(:tcg_engine_game_players)

    drop constraint(:tcg_engine_game_snapshots, "tcg_engine_game_snapshots_game_id_fkey")

    drop_if_exists unique_index(:tcg_engine_game_snapshots, [:game_id, :index],
                     name: "tcg_engine_game_snapshots_unique_game_snapshot_index_index"
                   )

    drop table(:tcg_engine_game_snapshots)

    alter table(:tcg_engine_games) do
      remove :status
      remove :updated_at
      remove :created_at
      remove :latest_event_index
      remove :cursor_index
      remove :first_player_id
      remove :active_player_id
    end

    drop constraint(:tcg_engine_prompts, "tcg_engine_prompts_game_id_fkey")

    drop constraint(:tcg_engine_prompts, "tcg_engine_prompts_turn_id_fkey")

    alter table(:tcg_engine_prompts) do
      modify :turn_id, :uuid
      modify :game_id, :uuid
    end

    drop constraint(:tcg_engine_setups, "tcg_engine_setups_game_id_fkey")

    alter table(:tcg_engine_setups) do
      modify :game_id, :uuid
    end

    drop constraint(:tcg_engine_turns, "tcg_engine_turns_game_id_fkey")

    alter table(:tcg_engine_turns) do
      modify :game_id, :uuid
    end

    drop table(:tcg_engine_games)

    drop table(:tcg_engine_prompts)

    drop_if_exists unique_index(:tcg_engine_setups, [:game_id],
                     name: "tcg_engine_setups_unique_game_setup_index"
                   )

    drop table(:tcg_engine_setups)

    drop_if_exists unique_index(:tcg_engine_turns, [:game_id, :turn_number],
                     name: "tcg_engine_turns_unique_game_turn_number_index"
                   )

    drop table(:tcg_engine_turns)
  end
end
