defmodule Prizmo.Repo.Migrations.AddTcgEvolutionState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tcg_engine_card_instances) do
      add :evolves_from_card_instance_id,
          references(:tcg_engine_card_instances,
            column: :id,
            name: "tcg_engine_card_instances_evolves_from_card_instance_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :turn_entered_play, :bigint
    end
  end

  def down do
    drop constraint(
           :tcg_engine_card_instances,
           "tcg_engine_card_instances_evolves_from_card_instance_id_fkey"
         )

    alter table(:tcg_engine_card_instances) do
      remove :turn_entered_play
      remove :evolves_from_card_instance_id
    end
  end
end
