defmodule Prizmo.Repo.Migrations.AddTcgFlowState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tcg_engine_games) do
      add :flow_state, :text, null: false, default: "pregame_awaiting_coin_toss"
      add :coin_toss_calling_player_id, :text
      add :coin_toss_call, :text
      add :coin_toss_result, :text
      add :coin_toss_winner_player_id, :text
      add :starting_player_chosen_by_player_id, :text
    end
  end

  def down do
    alter table(:tcg_engine_games) do
      remove :starting_player_chosen_by_player_id
      remove :coin_toss_winner_player_id
      remove :coin_toss_result
      remove :coin_toss_call
      remove :coin_toss_calling_player_id
      remove :flow_state
    end
  end
end
