defmodule Prizmo.Repo.Migrations.AddTcgAttackLifecycle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tcg_engine_turns) do
      add :pending_attack_id, :text
      add :pending_attacker_card_instance_id, :uuid
      add :pending_defender_card_instance_id, :uuid
    end
  end

  def down do
    alter table(:tcg_engine_turns) do
      remove :pending_defender_card_instance_id
      remove :pending_attacker_card_instance_id
      remove :pending_attack_id
    end
  end
end
