defmodule Prizmo.Repo.Migrations.AddTcgTurnLifecycle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tcg_engine_games) do
      add :winner_player_id, :text
    end
  end

  def down do
    alter table(:tcg_engine_games) do
      remove :winner_player_id
    end
  end
end
