defmodule Prizmo.Repo.Migrations.AddTcgTrainerMechanics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tcg_engine_game_players) do
      add :ace_spec_played_this_game?, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:tcg_engine_game_players) do
      remove :ace_spec_played_this_game?
    end
  end
end
