defmodule Prizmo.Repo.Migrations.AddTcgRngMetadata do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tcg_engine_games) do
      add :rng_seed, :text
      add :rng_seed_source, :text
      add :rng_algorithm, :text
    end
  end

  def down do
    alter table(:tcg_engine_games) do
      remove :rng_algorithm
      remove :rng_seed_source
      remove :rng_seed
    end
  end
end
