defmodule Prizmo.Repo.Migrations.AddTcgPendingEffects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tcg_engine_prompts) do
      add :pending_effect_id, :uuid
    end

    create table(:tcg_engine_pending_effects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:tcg_engine_prompts) do
      modify :pending_effect_id,
             references(:tcg_engine_pending_effects,
               column: :id,
               name: "tcg_engine_prompts_pending_effect_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tcg_engine_pending_effects) do
      add :game_id,
          references(:tcg_engine_games,
            column: :id,
            name: "tcg_engine_pending_effects_game_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :source_type, :text, null: false

      add :source_card_instance_id,
          references(:tcg_engine_card_instances,
            column: :id,
            name: "tcg_engine_pending_effects_source_card_instance_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :source_card_id, :text
      add :controller_player_id, :text, null: false
      add :current_player_id, :text
      add :effect_key, :text
      add :step, :text, null: false, default: "start"
      add :state, :map, null: false, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :status, :text, null: false, default: "pending"
    end

    create unique_index(:tcg_engine_pending_effects, [:game_id],
             name: "tcg_engine_pending_effects_one_awaiting_per_game_index",
             where: "status = 'awaiting_prompt'"
           )
  end

  def down do
    drop_if_exists unique_index(:tcg_engine_pending_effects, [:game_id],
                     name: "tcg_engine_pending_effects_one_awaiting_per_game_index"
                   )

    drop constraint(:tcg_engine_pending_effects, "tcg_engine_pending_effects_game_id_fkey")

    drop constraint(
           :tcg_engine_pending_effects,
           "tcg_engine_pending_effects_source_card_instance_id_fkey"
         )

    alter table(:tcg_engine_pending_effects) do
      remove :status
      remove :updated_at
      remove :created_at
      remove :state
      remove :step
      remove :effect_key
      remove :current_player_id
      remove :controller_player_id
      remove :source_card_id
      remove :source_card_instance_id
      remove :source_type
      remove :game_id
    end

    drop constraint(:tcg_engine_prompts, "tcg_engine_prompts_pending_effect_id_fkey")

    alter table(:tcg_engine_prompts) do
      modify :pending_effect_id, :uuid
    end

    drop table(:tcg_engine_pending_effects)

    alter table(:tcg_engine_prompts) do
      remove :pending_effect_id
    end
  end
end
